# Generated by Django 3.2.3 on 2021-05-28 13:43

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('document_code', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcode',
            name='overlay',
            field=wagtailmarkdown.fields.MarkdownField(blank=True),
        ),
    ]
