# Generated by Django 3.2.3 on 2021-05-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_code', '0002_alter_documentcode_overlay'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcode',
            name='document_code',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
