# Generated by Django 3.2.3 on 2021-05-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure_type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuretype',
            name='measure_type',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
