# Generated by Django 3.2.3 on 2021-05-28 17:25

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('measure_type', '0002_measuretype_measure_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuretype',
            name='overlay',
            field=wagtailmarkdown.fields.MarkdownField(blank=True),
        ),
    ]
