# Generated by Django 3.2.3 on 2021-05-28 22:42

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('signposting_step', '0003_signpostingstepcontainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signpostingstep',
            name='date',
        ),
        migrations.AlterField(
            model_name='signpostingstep',
            name='content_agent',
            field=wagtailmarkdown.fields.MarkdownField(blank=True),
        ),
        migrations.AlterField(
            model_name='signpostingstep',
            name='content_trader_declarant',
            field=wagtailmarkdown.fields.MarkdownField(blank=True),
        ),
        migrations.AlterField(
            model_name='signpostingstep',
            name='content_trader_nondeclarant',
            field=wagtailmarkdown.fields.MarkdownField(blank=True),
        ),
    ]
