# Generated by Django 3.2.3 on 2021-05-28 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signposting_step', '0005_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
