# Generated by Django 3.2.3 on 2021-05-28 23:51

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('signposting_step', '0007_auto_20210528_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signpostingsteptag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='signposting_step_tags', to='signposting_step.signpostingstep'),
        ),
    ]
