# Generated by Django 3.2.3 on 2021-05-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signposting_step', '0008_alter_signpostingsteptag_content_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='signpostingstep',
            name='priority',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
