# Generated by Django 3.2.3 on 2021-05-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signposting_step', '0009_signpostingstep_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signpostingstep',
            name='priority',
            field=models.IntegerField(blank=True),
        ),
    ]
