# Generated by Django 3.2.3 on 2021-05-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heading', '0002_heading_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='heading',
            name='link_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
