# Generated by Django 3.2.3 on 2021-05-28 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heading', '0004_superheading_superheadingcontainer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heading',
            options={'verbose_name': 'Results page subsection (or header)', 'verbose_name_plural': 'Results page subsections'},
        ),
    ]
