# Generated by Django 3.2.3 on 2021-05-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heading', '0005_alter_heading_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading',
            name='priority',
            field=models.IntegerField(blank=True),
        ),
    ]
