# Generated by Django 3.2.3 on 2021-05-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signposting_step', '0010_alter_signpostingstep_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='signpostingstep',
            name='sections',
            field=models.Field(blank=True, max_length=255, verbose_name='Linked to sections'),
        ),
    ]
