# Generated by Django 3.2.3 on 2021-05-29 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signposting_step', '0011_signpostingstep_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signpostingstep',
            name='sections',
        ),
    ]
